new Function(`
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const sampleItems=[
{id:'rc1',name:'kirmizi_araba_1.jpg',src:'assets/samples/red-car-1.svg',size:1840000,type:'image/svg+xml',lastModified:Date.now()-7*864e5,tags:['red','car','kirmizi araba'],demo:true},
{id:'rc2',name:'kirmizi_araba_2.jpg',src:'assets/samples/red-car-2.svg',size:2110000,type:'image/svg+xml',lastModified:Date.now()-4*864e5,tags:['red','car','kirmizi araba'],demo:true},
{id:'rc3',name:'kirmizi_araba_3.jpg',src:'assets/samples/red-car-3.svg',size:2020000,type:'image/svg+xml',lastModified:Date.now()-11*864e5,tags:['red','car','kirmizi araba'],demo:true},
{id:'rc4',name:'kirmizi_araba_4.jpg',src:'assets/samples/red-car-4.svg',size:1960000,type:'image/svg+xml',lastModified:Date.now()-2*864e5,tags:['red','car','kirmizi araba'],demo:true},
{id:'bs1',name:'mavi_atki_1.jpg',src:'assets/samples/blue-scarf-1.svg',size:1540000,type:'image/svg+xml',lastModified:Date.now()-18*864e5,tags:['blue','scarf','mavi atki'],demo:true},
{id:'bs2',name:'mavi_atki_2.jpg',src:'assets/samples/blue-scarf-2.svg',size:1490000,type:'image/svg+xml',lastModified:Date.now()-8*864e5,tags:['blue','scarf','mavi atki'],demo:true},
{id:'bs3',name:'mavi_atki_3.jpg',src:'assets/samples/blue-scarf-3.svg',size:1590000,type:'image/svg+xml',lastModified:Date.now()-5*864e5,tags:['blue','scarf','mavi atki'],demo:true},
{id:'wd1',name:'beyaz_guvercin_1.jpg',src:'assets/samples/white-dove-1.svg',size:1260000,type:'image/svg+xml',lastModified:Date.now()-24*864e5,tags:['white','dove','beyaz guvercin'],demo:true},
{id:'wd2',name:'beyaz_guvercin_2.jpg',src:'assets/samples/white-dove-2.svg',size:1320000,type:'image/svg+xml',lastModified:Date.now()-15*864e5,tags:['white','dove','beyaz guvercin'],demo:true}
];
const state={scope:'Galeri',route:{title:'Genel galeri analizi',text:'Tüm medya türlerini inceleyip düzenleme fırsatlarını belirleyeceğim.',query:'Galerimi düzenle',intent:'general'},files:[],analysis:null,selected:new Set(),currentRec:null,history:JSON.parse(localStorage.getItem('pilot_history_v33')||'[]'),albums:JSON.parse(localStorage.getItem('pilot_albums_v33')||'[]'),deletedIds:new Set(JSON.parse(localStorage.getItem('pilot_deleted_v33')||'[]'))};
function save(){localStorage.setItem('pilot_history_v33',JSON.stringify(state.history));localStorage.setItem('pilot_albums_v33',JSON.stringify(state.albums));localStorage.setItem('pilot_deleted_v33',JSON.stringify([...state.deletedIds]))}
function go(id){$$('.screen').forEach(el=>el.classList.toggle('active',el.id===id));$$('.nav').forEach(el=>el.classList.toggle('active',el.dataset.go===id));if(id==='albums')renderAlbums(); if(id==='history')renderHistory(); window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#goSettings').onclick=()=>go('settings');
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2000)}
function modal(title,body,withClose=true){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.add('show');$('#modalClose').style.display=withClose?'block':'none'}
$('#modalClose').onclick=()=>$('#modal').classList.remove('show');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('show')}
function fmt(n){if(n>=1e9)return (n/1e9).toFixed(1)+' GB'; if(n>=1e6)return (n/1e6).toFixed(n>1e8?0:1)+' MB'; return Math.max(1,Math.round(n/1e3))+' KB'}
function esc(s){return (s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}

function resetObjectUrls(items){items.forEach(it=>{if(it.objectUrl && it.releaseOnClear!==false){try{URL.revokeObjectURL(it.objectUrl)}catch(e){}}})}
function createItemsFromFiles(files){return files.filter(f=>!state.deletedIds.has(f.name+'_'+f.size)).map((f,i)=>{const isImg=(f.type||'').startsWith('image/'); const u=isImg?URL.createObjectURL(f):''; return {id:f.name+'_'+f.size+'_'+i,name:f.name,size:f.size||0,type:f.type||'application/octet-stream',lastModified:f.lastModified||Date.now(),src:u,objectUrl:u,demo:false,tags:guessTags(f.name)}})}
function guessTags(name){const n=(name||'').toLowerCase();const tags=[];if(/screenshot|screen|ekran|ss/.test(n))tags.push('screenshot');if(/video|vid|mov|mp4/.test(n))tags.push('video');return tags}

function parsePrompt(text){const n=text.toLowerCase().replace(/[ç]/g,'c').replace(/[ğ]/g,'g').replace(/[ı]/g,'i').replace(/[ö]/g,'o').replace(/[ş]/g,'s').replace(/[ü]/g,'u');
if(/gecmis/.test(n)) return {mode:'go',screen:'history',message:'Seni geçmiş ekranına yönlendirebilirim.'};
if(/pilot ornek|ornek album/.test(n)) return {mode:'sample',title:'Pilot Örnek Albümü',text:'Hazır örnek albümü anında tarayacağım.',query:text,intent:'sample'};
if(/kirmizi.*araba|araba.*kirmizi/.test(n)) return {mode:'smartSample',filter:'redcar',albumName:'Kırmızı Araba',title:'Kırmızı arabalı fotoğraflar',text:'Örnek albüm içinden kırmızı arabaları bulup albüm oluşturmaya hazırlayacağım.',query:text};
if(/mavi.*atki|atki.*mavi/.test(n)) return {mode:'smartSample',filter:'bluescarf',albumName:'Mavi Atkı',title:'Mavi atkılı fotoğraflar',text:'Örnek albüm içinden mavi atkılı görselleri bulacağım.',query:text};
if(/beyaz.*guvercin|guvercin.*beyaz|beyaz.*kus/.test(n)) return {mode:'smartSample',filter:'whitedove',albumName:'Beyaz Güvercin',title:'Beyaz güvercinli fotoğraflar',text:'Örnek albüm içinden beyaz güvercin görsellerini bulacağım.',query:text};
if(/ekran.*goruntu|screenshot|ss/.test(n)) return {mode:'route',title:'Ekran görüntülerini düzenle',text:'Ekran görüntülerini tarama sonrası tek yerde toplar ve aksiyon öneririm.',query:text,intent:'screens'};
if(/buyuk.*video|video.*buyuk/.test(n)) return {mode:'route',title:'Büyük videoları bul',text:'Büyük video dosyalarını öne çıkarırım.',query:text,intent:'large'};
if(/album/.test(n) && /tara/.test(n)) return {mode:'route',title:'Albüm tarama',text:'Belirli bir albüm seçmeni isteyeceğim.',query:text,intent:'album'};
return {mode:'route',title:'Genel galeri analizi',text:'İsteğini anlayabildim. Tarama alanını seçmeni isteyeceğim.',query:text,intent:'general'};}

function showAI(route){$('#aiPanel').classList.add('show');$('#aiTitle').textContent='Pilot yönlendirmesi';$('#aiText').textContent=route.text||route.message;const box=$('#aiSuggestions');box.innerHTML='';
if(route.mode==='go'){box.innerHTML=\\`<button class='suggestion'><span><strong>Geçmişi aç</strong><small>Önceki işlemlerini görebilirsin.</small></span><span class='badge'>Hazır</span></button>\\`;box.querySelector('button').onclick=()=>go(route.screen);return}
if(route.mode==='smartSample'){
 box.innerHTML=\\`<button class='suggestion'><span><strong>Örnek albümde ara</strong><small>${route.albumName} için akıllı eşleştirme yap.</small></span><span class='badge'>Örnek veri</span></button><button class='suggestion'><span><strong>Tarama alanını aç</strong><small>İstersen manuel olarak da galeri seçebilirsin.</small></span><span class='badge'>Manuel</span></button>\\`;
 const btns=box.querySelectorAll('button'); btns[0].onclick=()=>runSmartSample(route); btns[1].onclick=()=>applyRoute(route);
 return;
}
box.innerHTML=\\`<button class='suggestion'><span><strong>Tarama alanını aç</strong><small>${route.title}</small></span><span class='badge'>Önerilen</span></button>\\`;
box.querySelector('button').onclick=()=>applyRoute(route);
}

function applyRoute(route){state.route=route;$('#routeTitle').textContent=route.title;$('#routeText').textContent=route.text;$('#routeQuery').textContent=route.query||'';go('scan')}
$('#sendPrompt').onclick=()=>{const p=$('#prompt').value.trim(); if(!p){toast('Önce isteğini yaz'); return} const route=parsePrompt(p); showAI(route)};
$$('.chip').forEach(c=>c.onclick=()=>{$('#prompt').value=c.textContent; $('#sendPrompt').click()});

function runSmartSample(route){state.route={title:route.title,text:route.text,query:route.query,intent:'sample'}; state.scope='Pilot Örnek Albümü'; let items=sampleItems.filter(it=>!state.deletedIds.has(it.id)); if(route.filter==='redcar') items=items.filter(it=>it.tags.includes('red')||it.tags.includes('car')); if(route.filter==='bluescarf') items=items.filter(it=>it.tags.includes('blue')||it.tags.includes('scarf')); if(route.filter==='whitedove') items=items.filter(it=>it.tags.includes('white')||it.tags.includes('dove')); state.files=items.map(x=>({...x})); runScan(route.albumName)}

$('#btnSample').onclick=()=>{state.route={title:'Pilot Örnek Albümü',text:'Örnek veriyi analiz edeceğim.',query:'Pilot Örnek Albümü',intent:'sample'}; state.scope='Pilot Örnek Albümü'; state.files=sampleItems.filter(it=>!state.deletedIds.has(it.id)).map(x=>({...x})); runScan('Pilot Örnek Albümü')};
$('#btnAll').onclick=()=>$('#pickAll').click(); $('#btnFolder').onclick=()=>$('#pickFolder').click(); $('#btnAlbum').onclick=()=>$('#pickAlbum').click();
$('#pickAll').onchange=e=>loadPicked(e.target.files,'Tüm Galeri'); $('#pickFolder').onchange=e=>loadPicked(e.target.files,'Klasör'); $('#pickAlbum').onchange=e=>loadPicked(e.target.files,'Albüm');
function loadPicked(list,scope){const files=[...list]; if(!files.length){toast('Seçim yapılmadı'); return} state.scope=scope; resetObjectUrls(state.files.filter(f=>f.objectUrl)); state.files=createItemsFromFiles(files); runScan(scope)}

let scanToken=0;
function runScan(scopeTitle){scanToken++; const token=scanToken; go('scanning'); $('#scanTitle').textContent=scopeTitle+' inceleniyor'; let i=0, total=state.files.length, photos=0, videos=0, size=0; const chunk=Math.max(1,Math.ceil(total/22)); function step(){ if(token!==scanToken)return; const end=Math.min(total,i+chunk); for(;i<end;i++){const f=state.files[i]; size+=f.size||0; if((f.type||'').startsWith('video/'))videos++; else photos++; } const pct=Math.round((i/Math.max(total,1))*100); $('#bar').style.width=pct+'%'; $('#liveCount').textContent=i+' medya bulundu'; $('#liveSize').textContent=fmt(size)+' işlendi'; $('#livePhotos').textContent=photos; $('#liveVideos').textContent=videos; const partial=analyze(state.files.slice(0,i)); $('#liveFlags').textContent=partial.recommendations.length; $('#scanStatus').textContent=pct<35?'Medya türleri belirleniyor…':pct<70?'Boyut ve örüntüler hesaplanıyor…':'Öneriler hazırlanıyor…'; if(i<total) setTimeout(step,45); else {state.analysis=analyze(state.files); setTimeout(()=>{renderResults(); go('results')},250)} } step()}
$('#cancelScan').onclick=()=>{scanToken++; go('scan'); toast('Tarama iptal edildi')};

function analyze(files){const photos=files.filter(f=>(f.type||'').startsWith('image/')||String(f.type).includes('svg')), videos=files.filter(f=>(f.type||'').startsWith('video/')); const screens=files.filter(f=>/screenshot|screen|ekran|ss/i.test(f.name)); const large=files.filter(f=>(f.size||0) > ((f.type||'').startsWith('video/')?100e6:1.8e6));
const recs=[]; if(screens.length)recs.push({id:'screens',title:'Ekran görüntülerini ayıkla',desc:\\`${screens.length} ekran görüntüsü bulundu.\\`,items:screens,badge:'Orta güven',why:'Dosya adı örüntüsü'});
if(large.length)recs.push({id:'large',title:'Büyük medyaları incele',desc:\\`${large.length} büyük medya dosyası bulundu.\\`,items:large,badge:'Yüksek güven',why:'Boyut eşiği'});
const tags={redcar:files.filter(f=>f.tags&&f.tags.some(t=>/red|car|kirmizi araba/.test(t))), bluescarf:files.filter(f=>f.tags&&f.tags.some(t=>/blue|scarf|mavi atki/.test(t))), whitedove:files.filter(f=>f.tags&&f.tags.some(t=>/white|dove|beyaz guvercin/.test(t)))};
if(tags.redcar.length)recs.push({id:'redcar',title:'Kırmızı arabaları albümle',desc:\\`${tags.redcar.length} görsel kırmızı araba etiketiyle eşleşti.\\`,items:tags.redcar,badge:'Örnek veri',why:'Etiket eşleştirme'});
if(tags.bluescarf.length)recs.push({id:'bluescarf',title:'Mavi atkılıları albümle',desc:\\`${tags.bluescarf.length} görsel mavi atkı etiketiyle eşleşti.\\`,items:tags.bluescarf,badge:'Örnek veri',why:'Etiket eşleştirme'});
if(tags.whitedove.length)recs.push({id:'whitedove',title:'Beyaz güvercinleri albümle',desc:\\`${tags.whitedove.length} görsel beyaz güvercin etiketiyle eşleşti.\\`,items:tags.whitedove,badge:'Örnek veri',why:'Etiket eşleştirme'});
if(!recs.length && files.length)recs.push({id:'organize',title:'Medyaları düzenle',desc:\\`${files.length} medya için albüm ve işlem akışı hazır.\\`,items:files,badge:'Hazır',why:'Genel analiz'});
return {files,photos,videos,screens,large,total:files.reduce((s,f)=>s+(f.size||0),0),recommendations:recs}}

function renderResults(){const a=state.analysis; $('#headline').textContent=a.recommendations.length+' fırsat bulundu'; $('#subline').textContent=\\`${a.photos.length} fotoğraf ve ${a.videos.length} video analiz edildi.\\`; $('#scope').textContent=state.scope; $('#mMedia').textContent=a.files.length; $('#mSize').textContent=fmt(a.total); $('#mRisk').textContent=a.recommendations.length; $('#recCount').textContent=a.recommendations.length+' öneri'; $('#recommendations').innerHTML=a.recommendations.map(r=>\\`<div class='rec card'><div class='top'><div><h4>${r.title}</h4><p>${r.desc}</p></div><span class='badge'>${r.badge}</span></div><div class='meta'><span class='tag'>${r.items.length} öğe</span><span class='tag'>${fmt(r.items.reduce((s,f)=>s+(f.size||0),0))}</span><span class='tag'>${r.why}</span></div><div class='actions'><button class='small' data-why='${r.id}'>Neden?</button><button class='small primary' data-open='${r.id}'>Aç</button></div></div>\\`).join('');
$$('[data-why]').forEach(b=>b.onclick=()=>{const r=a.recommendations.find(x=>x.id===b.dataset.why); modal(r.title,\\`<p><b>Tespit yöntemi:</b> ${esc(r.why)}.</p><p>Pilot bu bulguyu öneri olarak sunar; son karar sende kalır.</p>\\`) });
$$('[data-open]').forEach(b=>b.onclick=()=>openOperation(a.recommendations.find(x=>x.id===b.dataset.open)));}
$('#openReport').onclick=()=>{const a=state.analysis; const top=[...a.files].sort((x,y)=>(y.size||0)-(x.size||0)).slice(0,6); $('#reportBody').innerHTML=\\`<div class='card' style='padding:18px'><h3 style='margin:0 0 10px'>Medya dağılımı</h3><div class='metrics'><div class='metric'><b>${a.photos.length}</b><span>Fotoğraf</span></div><div class='metric'><b>${a.videos.length}</b><span>Video</span></div><div class='metric'><b>${fmt(a.total)}</b><span>Toplam boyut</span></div></div></div><div class='card' style='padding:18px'><h3 style='margin:0 0 10px'>Bulunan kümeler</h3><div class='tags'>${a.recommendations.map(r=>\\`<span class='tag'>${r.title} · ${r.items.length}</span>\\`).join('')}</div></div><div class='card' style='padding:18px'><h3 style='margin:0 0 10px'>Ön izleme</h3><div class='filegrid'>${top.map(it=>thumbHTML(it)).join('')}</div></div>\\`; go('report')};
function thumbHTML(it){return \\`<div class='thumb card'><img src='${it.src||''}' alt=''><div class='thumbinfo'><b>${esc(it.name)}</b><span>${fmt(it.size)} · ${new Date(it.lastModified).toLocaleDateString('tr-TR')}</span></div></div>\\`}

function openOperation(rec){state.currentRec=rec; state.selected=new Set(rec.items.map((_,i)=>i)); $('#opTitle').textContent=rec.title; $('#opDesc').textContent='Seçili öğeler için albüm oluşturma, taşıma, kopyalama veya silme işlemi uygulayabilirsin.'; renderOperation(); go('operation')}
function renderOperation(){const items=state.currentRec.items; $('#opList').innerHTML=items.map((f,i)=>\\`<div class='fileitem ${state.selected.has(i)?'selected':''}' data-i='${i}'><span class='ficon'>${(f.type||'').startsWith('video/')?'▶':'▧'}</span><span><b>${esc(f.name)}</b><span class='meta'>${fmt(f.size)} · ${new Date(f.lastModified).toLocaleDateString('tr-TR')}</span></span><span class='check'>${state.selected.has(i)?'✓':''}</span></div>\\`).join(''); $$('#opList [data-i]').forEach(el=>el.onclick=()=>{const i=+el.dataset.i; state.selected.has(i)?state.selected.delete(i):state.selected.add(i); renderOperation()})}
$('#toggleAll').onclick=()=>{const n=state.currentRec.items.length; state.selected.size===n?state.selected.clear():state.selected=new Set([...Array(n).keys()]); renderOperation()}
function getSelectedItems(){return state.currentRec.items.filter((_,i)=>state.selected.has(i))}
function askAlbum(action, handler){const options=state.albums.map(a=>\\`<option value='${esc(a.name)}'>${esc(a.name)}</option>\\`).join(''); modal(action==='create'?'Yeni albüm oluştur':action==='move'?'Taşınacak albümü seç':'Kopyalanacak albümü seç', action==='create'?\\`<p>Seçili öğeler için yeni albüm adı gir.</p><input id='albumName' placeholder='Örn. Kırmızı Araba'>\\`:\\`<p>Hedef albümü seç veya yeni ad yaz.</p><select id='albumSelect'><option value=''>Albüm seç</option>${options}</select><input id='albumName' placeholder='veya yeni albüm adı yaz'>\\`, false); $('#modalBody').insertAdjacentHTML('beforeend',\\`<div class='btnrow'><button class='btn' id='okAction'>Devam et</button><button class='btn3' id='cancelAction'>Vazgeç</button></div>\\`); $('#cancelAction').onclick=()=>$('#modal').classList.remove('show'); $('#okAction').onclick=()=>{const fromSelect=$('#albumSelect')?$('#albumSelect').value:''; const name=($('#albumName')?.value||'').trim() || fromSelect; if(!name){toast('Albüm adı gerekli'); return} $('#modal').classList.remove('show'); handler(name)} }
function ensureAlbum(name){let album=state.albums.find(a=>a.name===name); if(!album){album={id:'alb_'+Date.now()+Math.random().toString(36).slice(2,6),name,items:[]}; state.albums.unshift(album)} return album}
function addToAlbum(name,items,removeFromCurrent,kind){const album=ensureAlbum(name); const existing=new Set(album.items.map(x=>x.id)); items.forEach(it=>{if(!existing.has(it.id))album.items.push({...it})}); if(removeFromCurrent){removeItems(items,false)} const k=kind || (removeFromCurrent?'Taşıma':'Kopyalama'); record(k,\\`${name} albümüne ${items.length} öğe\\`,items.length); save(); renderAlbums(); toast(k==='Albüm oluşturma'?'Albüm oluşturuldu':(removeFromCurrent?'Öğeler taşındı':'Öğeler kopyalandı')); go('albums')}
function removeItems(items,recordIt=true){const ids=new Set(items.map(i=>i.id||i.name+'_'+i.size)); items.forEach(it=>state.deletedIds.add(it.id||it.name+'_'+it.size)); state.analysis.files=state.analysis.files.filter(f=>!ids.has(f.id||f.name+'_'+f.size)); state.currentRec.items=state.currentRec.items.filter(f=>!ids.has(f.id||f.name+'_'+f.size)); state.albums.forEach(a=>a.items=a.items.filter(f=>!ids.has(f.id||f.name+'_'+f.size))); state.analysis=analyze(state.analysis.files); if(recordIt) record('Silme',\\`${items.length} öğe kaldırıldı\\`,items.length); save(); renderResults(); renderOperation(); renderAlbums();}
function record(action,subject,count){state.history.unshift({action,subject,count,time:Date.now()}); save(); renderHistory()}
$('#actCreate').onclick=()=>{const items=getSelectedItems(); if(!items.length){toast('Önce öğe seç');return} let defaultName='Yeni Albüm'; if(state.currentRec.id==='redcar')defaultName='Kırmızı Araba'; if(state.currentRec.id==='bluescarf')defaultName='Mavi Atkı'; if(state.currentRec.id==='whitedove')defaultName='Beyaz Güvercin'; modal('Yeni albüm oluştur',\\`<p>Seçili ${items.length} öğe için albüm adı gir.</p><input id='albumNew' value='${defaultName}'>\\`,false); $('#modalBody').insertAdjacentHTML('beforeend',\\`<div class='btnrow'><button class='btn' id='okCreate'>Albümü oluştur</button><button class='btn3' id='cancelCreate'>Vazgeç</button></div>\\`); $('#cancelCreate').onclick=()=>$('#modal').classList.remove('show'); $('#okCreate').onclick=()=>{const name=$('#albumNew').value.trim(); if(!name){toast('Albüm adı gir'); return} addToAlbum(name,items,false,'Albüm oluşturma'); $('#modal').classList.remove('show')}};
$('#actMove').onclick=()=>{const items=getSelectedItems(); if(!items.length){toast('Önce öğe seç');return} askAlbum('move',name=>addToAlbum(name,items,true))};
$('#actCopy').onclick=()=>{const items=getSelectedItems(); if(!items.length){toast('Önce öğe seç');return} askAlbum('copy',name=>addToAlbum(name,items,false))};
$('#actDelete').onclick=()=>{const items=getSelectedItems(); if(!items.length){toast('Önce öğe seç');return} modal('Silmeyi onayla',\\`<p><b>${items.length} öğe</b> Pilot içindeki mevcut çalışma listesinden kaldırılacak. Örnek albümde ve uygulama içi kayıtta tepki anında uygulanır.</p>\\`,false); $('#modalBody').insertAdjacentHTML('beforeend',\\`<div class='btnrow'><button class='btnDanger' id='okDelete'>Sil</button><button class='btn3' id='cancelDelete'>Vazgeç</button></div>\\`); $('#cancelDelete').onclick=()=>$('#modal').classList.remove('show'); $('#okDelete').onclick=()=>{$('#modal').classList.remove('show'); removeItems(items); toast('Seçili öğeler kaldırıldı'); go('results')}};

function renderAlbums(){const data=[{name:'Pilot Örnek Albümü',items:sampleItems.filter(it=>!state.deletedIds.has(it.id)),fixed:true},...state.albums]; $('#albumGrid').innerHTML=data.length?data.map(a=>\\`<div class='album card' data-album='${esc(a.name)}'><div class='albumhead'><span class='badge'>${a.fixed?'Örnek':'Kullanıcı'}</span><span class='tag'>${a.items.length} öğe</span></div><h4>${esc(a.name)}</h4><p>${a.fixed?'Test ve demo için hazır örnek küme.':'Pilot tarafından oluşturulan albüm.'}</p><div class='coverstack'>${a.items.slice(0,4).map(it=>\\`<img src='${it.src||''}' alt=''>\\`).join('') || \\`<div class='empty'>Boş</div>\\`}</div></div>\\`).join(''):\\`<div class='empty card'>Henüz albüm yok.</div>\\`; $$('#albumGrid [data-album]').forEach(el=>el.onclick=()=>openAlbum(el.dataset.album))}
function openAlbum(name){const album=name==='Pilot Örnek Albümü'?{name,items:sampleItems.filter(it=>!state.deletedIds.has(it.id))}:state.albums.find(a=>a.name===name); modal(album.name,\\`<p>${album.items.length} öğe içeriyor.</p><div class='filegrid'>${album.items.slice(0,6).map(it=>thumbHTML(it)).join('')}</div>\\`)}
function renderHistory(){ $('#historyList').innerHTML=state.history.length?state.history.map(h=>\\`<div class='historyitem'><span class='hicon'>✓</span><span><b>${esc(h.action)}</b><p>${esc(h.subject)} · ${h.count} öğe<br>${new Date(h.time).toLocaleString('tr-TR')}</p></span></div>\\`).join(''):\\`<div class='empty'>Henüz kayıt yok.</div>\\`}
$('#clearHistory').onclick=()=>{state.history=[]; save(); renderHistory(); toast('Geçmiş temizlendi')}
renderAlbums(); renderHistory();
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}
`); console.log("OK")